### ISSUE TITLE
[Umbrella Issue] Project Ideas

### ISSUE THREAD

**Issue by dhavalgshah** [dhavalgshah/learning-golang#1]
Listing all the project ideas I can gather. From small stuff to complex projects.

# Tiny
- [ ] DNS checker
- [ ] whois checker
- [ ] ip lookup (own public, own private, ip, or domain)
- [ ] SSL cert revocation  checker
- [ ] YAML parser

# Intermediate
- [ ] Tic-tac-toe game
- [ ] WebPageTest locations status
- [ ] Basic TimeTracker
- [ ] Simple Currency Conversion
- [ ] Persistence Key-Value store
- [ ] Discord/Slack/Twitter Remind Me Later Bot

# Hard
- [ ] HTTP Crawler
- [ ] Bitcoin & Currency Ticker
- [ ] Newsletter [cli + webapp]
- [ ] Sudoku Puzzle
- [ ] Calendly Clone [cli + webapp]

# Long Term
- [ ] Port WebPageTest [cli + webapp]
- [ ] Port HasGeek to Go (https://github.com/hasgeek/funnel)
